<div contenteditable="true">

	<p class="sizelabel">Source: Context of Diacritics http://urtd.net/projects/cod/</p>
	<p>&nbsp;</p>
		
	<p class="sizelabel">Afrikaans</p>
	<p style="font-size: 32px;">rêrig geïmplementeer gedefiniërde lêer primêre prinsipiëel sinaïwoestyn húlle ónder geëufemiseer geïsoleerde môre geïdentifiseer asiëoorlog dít sôre té appèl paleosoïkum geëmigreer appèl díé vóór wél óf plasmaproteïen reënboognasie tetraëdriese wîe reënboognasie nádat bó môre kontinuïteit hê óm adéliepikkewyn kaïro geïoniseer trôe adéliepikkewyn wêreldstelsels kêrel voëls hoëveldplato brûe vóór álle één mý</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Albanian</p>
	<p style="font-size: 32px;">bashkëqendrorë gjysmëboshtet këllyçit açuge sapoçliruar çeku njëkohësisht trashëgimtarët moskokëçarëse biçakçinjtë bashkëjetese qindvjeçarëve gjithçkaje çmoheshin trashëgimisë viçët përgjithësisht nxënësit pëlhurë çika përfaqësohet çdo pasçlirimit kinezçe bëmë mëllenjë këndvështrimi nënave çpronësim intelektualëve shëndet françeskanë përçueshmëri çfarosje njëanshmërinë termobërthamor togë përafërsisht shkencëtarët katërmbëdhjetë menjëhershëm çrregullimeve përgjithësisht thëologji dojçland kuçedër qindvjeçarëve malçan ndriçoheshin frashërllinjtë</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Catalan</p>
	<p style="font-size: 32px;">extraordinària periòdicament conseqüències abreugés enganxés súbdit hidroclàstia lúzula arboç búfal només esbós oceàniques fàcilment diplomàtiques iniciéssiu heroïcitat gaüssos cuscús específicament farmacèutic garfiüda noümen napoleó implícitament saüc filosòficament poètic litúrgics heterocíclics asfíxia aristotèliques recórrer empíriques jóvens heliòcèntrica estratègies aprenguérem dèbil elèctriques despropòsits aminoàcid alienígenes jurisprudència anaeròbiques aprehén welwítsquia astrofísica caòtic pertanyé</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Croatian</p>
	<p style="font-size: 32px;">ranokršćanske raspoređene tisućljećja prvovjenčanog obilježavanju veksikološkoj olakšavanje prebrođivanju višestoljetnog južnočakavskom brežuljkasti dobroćudnost karađorđevića hž osvrćući predsjedničkim predškolskog grožđa solženjicina bespomoćnost predsjedničkim očekivanjima švicarskoj dušobrižništvo poistovjećuje krijumčarenje najsačuvaniji najznačajniji ječma nešto iznenađujućom izčistimo karađorđevića zaključcima kćerkom korčulanskom šokčevića apolitičnošću podčinjena između uspostavivši priključenje zapamćena pregrađivanjem predviđanjima približavaju obilježjima šižgorićevo dubrovčanima iznenađujućom</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Czech</p>
	<p style="font-size: 32px;">frýdlantský jámy dvoušroubovicové jednoděložných experimentálních zčtyřnásobil trojúhelníkový zbídačených neuspořádaného nenasvědčují svébytnost afroameričané múzických proteosyntézy podezřelého nadlehčována ditrichštejna předchozích přenositelností návštěvníkem grónským hú přenositelností shromažďování výpůjčkami endosymbiózou nashromážděním zbývajících zajišťujících buďto šestiúhelníku býložravci nejrůznějších nashromážděním nonkonformistů nejdůležitější technologickému paměťové zemřelých vždyť středoškolské velkolepých předpokládají nejrozšířenějším ohňovou babyloňanům člověk londýnského místopředseda ovlivňovány</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Danish</p>
	<p style="font-size: 32px;">allerøstligste toårige småplaneter håndvasken næringsstoffer idégrundlaget saltvandsområde markedsøkonomi orkneyøerne navneændringen livsvilkårene gråzone solformørkelse nexø miljøændringer hurtigtkørende trææske løveburet forhøjningerne forhøjningerne sundhedsmæssig repræsentation overvågninger forudsætninger forårsjævndøgn vinnuháskúlin sammentrækning småøer månelanding miljøpolitisk tilbagestående masseuddøen nedbørsmængden våbenloven søfiskeriet månelandingen traktatmæssige opdagelsesåret miljøområdet europæisk sommerhalvåret kæmmekammen sammenhængende atacamaørkenen påvirkninger boligstøtten forårsjævndøgn oversvømmelser forudsætninger rensdyrjægerne</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Dutch</p>
	<p style="font-size: 32px;">elsloërbos geïoniseerde faeröer köppen tijdcontinuüm dààr daarvóór chambéryzomer yucatán roodcrème hypercalciëmie bètadeeltjes enquête émile ampère netcoördinator föhn solocarrière geëerbiedigd zó geïnteresseerd geïnteresseerd matthäus régime continuïteit müller lösslandschap solocarrière geïllustreerd netcoördinator dáár synapomorfieën führer cyanobacteriën namibiëwateren lievelingscafé valérie daarvóór géén méér scènes synapomorfieën triëste caraïbische adèle limbörgs luïciüs döner mineraloïden tröckener</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Estonian</p>
	<p style="font-size: 32px;">ebatõenäoline kogukonnavärav õhutemperatuur päritolusõnaks lepingusätteid aserbaidžaani päikeseööpäeva päikeseööpäeva hõimurahvaste keevitustööde dušš bolševistlikul päikeseööpäeva sünonüümidena süvakivimeid peipsiäärsetel jämedateralisi ligipääsematus akaatsiaõunaks lõunapolaarala tööõnnetus mõjusfäärideks kahelööviline tehnikaülikool suurvürstiriik ebatõenäoline polütehnilises aadlisuguvõsad löögiarmeedeks tänapäevastest tõkendvägedega büroo fetišism suveräänsusele tõrjevahendina kartulipõldude alljärgnevates nöörkeraamika apokrüüfid ühisgümnaasium näidissovhoosi höövel kogukonnavärav kašmiir tööhõiveamet pöördelisemaks kirikuõpetajad kliimavöötmed astrofüüsikute jaaniööl</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Finnish</p>
	<p style="font-size: 32px;">kansainvälisen långnäsiin lämpöydinpommi snežnogorskin pääaineksenaan tadžikistanin röntgensäteily väestöongelman bådankaarre pašša radiohäiriöitä kädenvääntöä käyttökohteita baškortostan näyttelijöistä ylänköalueilla wärtsilä šintolaisia šokki höyrystymiseen hengitettäessä mantšurian tähtitieteessä koneöljy lämpöydinpommi käyttöönottoa bassoäänien föhntuuli jyrängönvirta mårtenson långnäsiin pellavaöljy mažeikiain yhteislähdöstä grebeškov rikša heimopäällikkö ylösnousemusta keskilämpötila kääpiögalaksia jubytšvumtšorr tadžikistanin radiohäiriöitä stratosfääriin šamanistinen rahamääräisenä snežnogorskin yöbussi etsintäohjelma polttoöljyä</p>
	<p>&nbsp;</p>
	<p class="sizelabel">French</p>
	<p style="font-size: 32px;">prolifération revêtement hakkôda nivôse démêler empêchèrent huîtres müller créèrent ambigüité considèrent où herzégovine nîmois préjudiciables rœulx précipitations effectuèrent porphyrogénète reçoivent œdèmes grünen mûrissement convoyèrent contiguïté métamorphiques dû archevêque citroën propriétaires jérusalem phénoménologie prônant renâclent lærdal vêpres citroën préhistoriques angoulême stœchiométrie précipitations fraîche jürgen oùune parallèlement châtaignier nivôse hallucinogènes hawaïennes gênants</p>
	<p>&nbsp;</p>
	<p class="sizelabel">German</p>
	<p style="font-size: 32px;">flüstern großwild makroökonomie wirkungsgefüge fußabdruck unterstützung anständig umbaumaßnahme möglicherweise spötter füße fußpunkte körper einsaugöffnung kohleflöz dreißigjährig präzisierung entschädigung alttertiär volkstümlich eingeschränkt flussmündung eingebürgert unregelmäßig jüdisch gießverfahren religiös berücksichtigen cöllnisch gegenüber homöopathie blöße getöse programmäquivalenz frischkäse näherung schöngeistig grundsätzlich vernachlässigt schweißdrüsen südöstlich entblößen schönheit elektrizität ruderfußkrebs südlich nordeuropäer aktivität wortschöpfung neueröffnung</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Hungarian</p>
	<p style="font-size: 32px;">csicseriborsót ellenállásának szurdokpüspöki somogydöröcske fényszennyezés időszámításunk szilikátköpeny gabonaőrlő bázisidőszakra haszonnövénnyé síkfelületeken pihenőövezet röjtökmuzsaj napraforgóolaj aláírásával összefüggésben keletkezésével következtetünk ráesett testhosszúságú irányítótorony tengerszinttől hasadékvölgyek keresztülfolyó világháborúban konföderációja tulajdonképpen következtetünk előőrsként részecskéinek munkapéldánya műalkotásokban indexásványok bányaüzemben fölállításánál tartályhajókon rádióállomásai makroszkóposan világháborúig szivattyútelep refúgiumokban világszervezet görögországtól síkfelületeken zsiradékmentes mezozoós magnitúdóval tulajdonságúak lemezserpenyők törpebolygónál</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Icelandic</p>
	<p style="font-size: 32px;">áætlun óaðgengilegur landamæri samþing slétt nýaldar borgarsamfélög leiðöngrum þverfræðilegt hýsill áframhald héraðsstjórnum biblíuþýðing þætti póstmódernískt náttúruöfl malajíska bandaríkjadalur handahófsvalin póstur báxít kákasusfjöll glæpur uppgötvun ævisaga trúverðugleiki skæruhernaður tækniþróun hléum meðalúrkoma ævintýri pýreneafjöllum hnöttur þýskuþrautinni pílukast latínuskóli silfurgljáa sýndarþvermál aröbum handahófsvalin sæhestur óvéfengjanlegu útvegur latínukunnátta andrúmsloft alþjóðasamband guðmundsdóttir stjarnfræðinga frumgyðistrú hléi</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Italian</p>
	<p style="font-size: 32px;">piè privèe naïf rappresentò pressoché privèe  réclame bohémien luà perù regalìa màrtiri partecipò privée concepì glacière acconsentì trasformò contribuì purè seppellì ahimè système mammì princìpi pètsà sofà manzù pavé décolleté spécialisé équipe già cefalù marajà autodefinì promodès subìto conservò sottolineò assorbì mondovì passé pelè ciò saccà réunion più katmandù approfondì</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Latvian</p>
	<p style="font-size: 32px;">lūsis lēņtiesiskā pūčveidīgajiem čingizhans atpakaļceļā režģu basģitāra visnežēlīgākā pūčveidīgajiem nozīmīgākais āķīgs vējš reorganizācija profesionāļiem centrālvidzemē krīze karakuģa šervūda lielkņazistes patstāvīgais sociālais centrālāzija trūcīgs šķērsgriezums pārģērbjoties atsevišķajiem krūmāji austrumķīnas robežšķirtnes stratēģiskajām arhipelāgiem apģērbs bijušais poētiskos mežsaimniecībā republikāņiem līnija maģāru žokļžauņzivis apakšstruktūra ziemeļjūra priekšlasījumi austrumķīnas skrimšļzivīs augšģermānijas starptautiskās noārdoties nesaskaņotību hempšīra ceturdaļfinālu</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Lithuanian</p>
	<p style="font-size: 32px;">išsidėsčiusios išplaunamieji principų įgyvendindamas griežčiausiai viršutiniąja patręšdama patriarchą bendradarbį pasižyminčioje prancūziškai šienapjūtė laivų nepaklūstantys užfiksuojami vėplys intelektualų viršutiniame užžėlusios konservatyvūs pusiaužiemį neatidėliotinų pajacų apskaičiavimai susimaišęs ramūnelėmis lengvabūdiškai čadra nebegrįžtamas trąšas neatidėliotina gelžbetoniniai troleibusų priešžiemio karaliaučiuje geografų tranšėjinio rančą centrfūga džiūgaujančios užsandarinamas hipotezę perviršį spermatogenezė perkrovą įregistruotas praūžia kryždirbystė pasipriešinimo priežastingumo</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Maltese</p>
	<p style="font-size: 32px;">jitħallsu iżraeljan iżvolġiment neċessarjament jsejħulha xogħolijiet ġużè ċrieket jissejjaħ ġoswè kummerċjali idaħħluhom meħtieġa ażerbajġan boċċoċ tagħhom illużjonijiet xogħlijiet mosè bħalma oriżontali farmaċewtika rebaħx imrażżna kartaġni imħaffra rappreżentanza ħwieġ kċina oriġinarjament ħbieb sbuħija ġliem reliġjonijiet żewġt jissaħħnu kopenħagen ġmielu ċnisa ornitoloġiċi suċċessivament gżejjer ġurisdizzjoni pellegrinaġġi jixħet interfaċċa  gġant jagħmlulu digà jilleġiżla</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Norwegian</p>
	<p style="font-size: 32px;">understøtter fødselsåret leidangsflåte vågehvalfangst lavaørkener pygméer fireårsperiode råolje savannehøyland båtproduksjon sjøforsvaret utenforstående stålskjeletter søratlanteren skælingsfjall obskøniteter oversvømmelser klæbu makroøkonomisk soberanía reykjavík arrangørene biologiøkonomi hovedråsaker konsertpaléet toårige tertiærtiden kjønnsnøytrale sentralkomité rentebærende sentralområdet landsforræderi højer formålsrettet reléstasjon cæsar hærstyrker handelsgårdene køpmannæhafn sjåføren båhuslen krigserklæring råull verdensberømte válgabiire vågehvalfangst primærkilden markedsøkonomi vulgærlatin grønlandshavet</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Polish</p>
	<p style="font-size: 32px;">męczenników mózgowia przyciągnięcia niedostępności mścisław międzychód strzechą kriowulkanów błeszyńskiego bazyleę rodzimowierców ćwierćfinale zatytułowanym społeczeństwem żółć kopalń rzeczpospolitą sędziówponad przeciążonego niezbędnych jednomyślności doświadczeniem przybliżeniu zgęszczające częściowoukład rozczłonkowany problematykę utożsamianym ukształtowanie objętościowej włókienniczej sztućców ekozarządzanie długotrwałego rozpowszechnić wróblewskiego rzeczywistości organizowałby uśrednieniem liceów infrastrukturę październikowa przekształcana przyśpieszyły idźkowskiego niebędących maćkała sztućców współrzędnych międzynarodowa</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Portuguese</p>
	<p style="font-size: 32px;">intervenções linfáticos secundário protuberância rojões hidrofóbica revolucionária tufões galápagos científica água independência política religiões pão organoléptica açude sermões número espanhóis imprescindível cósmico intermediário albânia hiperbólica múltiplo propôs significância reminiscências atmosférico incontinência arquitectónico esporádico metalúrgica galáxia empréstimo atlântica órfãos cão boêmio característica afeganistão ausência meteoróides refúgio braquiópodes relíquias aúde empréstimo húmido</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Romanian</p>
	<p style="font-size: 32px;">gospodăriilor curcănaș isarlâk râzând descîntoteca îi pașalâcul câștigătorilor mișcătoare landșafturi declanșând caracterizează câteodată susținătorii maramureșului măgăoaie ortodocșii grădișteanu arnăuțoiu îndrăzneala nepermițând nutriționiști preoților învățământului batanovți gâdilătură achiziționând îți supraîncărcați îndatoririle învățământului sămănătorului absorbți încurajând adâncituri frumoși încălțăminte vâscozitate postăvar declanșator interacțiunea neobișnuitul manifestând doborâți bevșúg viețuitoarelor măsurătorilor varașdinul săgeata sazîkin</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Slovak</p>
	<p style="font-size: 32px;">hrubé odstupňovanie vrakuňský spracovateľský vyvýšených rozptýleného koňský systematického nadľudia päťstopým primiešaným vyústeniu rozpúšťadlá stredomaďarská odtiaľto euroázijského vďačíme chalcedónových sága päťpodlažný zasväcovali veľkokniežaťom rozpúšťadlá ekvivalentných severovýchodne zabezpečujúcim obdĺžnikovým čŕt náboženstvom kníhtlačiareň porfýrov manažmentom lži najvyššieho chalcedónových obkľúčeného zdokonaľovanie neptún karcinogénnym znečisťovania zväčšujúcou reliéf prapôvodnej súradniciach oranžovú najčistejšieho fúga zrážkomer užhorodská nemôže</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Slovenian</p>
	<p style="font-size: 32px;">razmnožujočih večkulturnost srednjenemška večstrankarske večfunkcijska lepšo družba priključevati koncentrično večceličnost olepševa domžale bogoslužje mehčanje maloštevilčna najpopolnejših načrtovanje žrtvenik marža osredotočeno južnoslovanski predkrščansko prekupčevalci požigalništvo stožčast višješolsko bližnjevzhodna korošci privlačnost najpomembnejše odžvepljevalne izobraževalni obžalovanje neandertalčeva predstavniško najpomembnejše protipožarno keltščina večdnevna špediter nevretenčarjev življenjsko rimokatoličani žgolenje južnoslovanski socialistično križpotja spužvarstvo ponemčevanje preprečujejo</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Spanish</p>
	<p style="font-size: 32px;">flúor epidémicas extraídos característico económicamente fotosintéticas antigüedad recíprocamente ibáñez fotoautótrofos lingüístico electrólisis análogamente fluorhídrico marginocéfalos búsqueda entregándose electrolíticas psíquicas albañilería meteorológicos méxico lambeosáuridos náhuatl quetzalcóatl devónico interpretación caóticos peláez tomatoroña paisajísticos océanos describía históricamente colorées exóticas aéreos geoestratégica intergaláctico clásicamente autótrofos astromóviles lingüistas apoyándose súbitamente mayúsculas almuñécar compañías acústico terráqueo</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Swedish</p>
	<p style="font-size: 32px;">bronsålderns skådespelarna otillgängligt plånböcker spöksonaten paté kanarieöarna överensstämmer båtgravsfynden tillfångatogs entréportalen fångtransport boskapsskötsel rättigheterna jülichs odyssé hjälmarebygden über kritikersuccé sjöförbindelse högkommissarie mót månghundraårig herjárdalr sönerna östersjökusten missnöjesparti sjuårskriget väderspänning lagkonståkning hushållsavfall upprätthållas kännetecknades väj spécial klubblagsnivå nödvändigheten därutav kravallsköldar åderbråck återuppväcktes färdigställdes snöbollsjorden nödsituationer inbördeskriget väderprognoser nyårsdagen stenåldern huvudredaktör tillväxtpakten</p>
	<p>&nbsp;</p>
	<p class="sizelabel">Turkish</p>
	<p style="font-size: 32px;">dönüştürmüştür oyçokluğuyla birleşiklikten türkçeçoğunluk teçhizatıyla paylaşmaktadır sağlandığından gösterdiğinden gözlemlerinden açıklamalardan övünmekteydi şövelyeleri dönüşümleridir çevrelenmiştir koşullarındaki selçukluların ağzından ögelerinden eşyıldızından başbakanlığına hiçbirinin dağtekin çürütmüşlerdir direktörlüğünü keşşaflığın çözülmesinde durdurulmuştur dönüşümleridir istenildiğinde sükûti ödenmeksizin musıkîyi seçkinlerin yoğunlaşamamış imparatorluğa boşaltılmıştır milliyetçilik götürülmüştür harezmşahların büyükşehirler köfteler konfiçyüscüler tarihçilerinin antrenörlüğünü mücadelelerine kâşif içtihatlarına eşcinselleri parlâmentoya kutalmışoğlu</p>
	
</div>	