<div>
	<p class="sizelabel" style="margin-bottom: 10px;">32px Most common letter sequences http://norvig.com/mayzner.html</p>
	<table width="900px">
		<tbody>
			<tr>
				<td valign="top">
					<p>e<br />
					t<br />
					a<br />
					o<br />
					i<br />
					n<br />
					s<br />
					r<br />
					h<br />
					l<br />
					d<br />
					c<br />
					u<br />
					m<br />
					f<br />
					p<br />
					g<br />
					w<br />
					y<br />
					b<br />
					v<br />
					k<br />
					x<br />
					j<br />
					q<br />
					z</p>
				</td>
				<td valign="top">
					<p>th<br />
					he<br />
					in<br />
					er<br />
					an<br />
					re<br />
					on<br />
					at<br />
					en<br />
					nd<br />
					ti<br />
					es<br />
					or<br />
					te<br />
					of<br />
					ed<br />
					is<br />
					it<br />
					al<br />
					ar<br />
					st<br />
					to<br />
					nt<br />
					ng<br />
					se<br />
					ha<br />
					as<br />
					ou<br />
					io<br />
					le<br />
					ve<br />
					co<br />
					me<br />
					de<br />
					hi<br />
					ri<br />
					ro<br />
					ic<br />
					ne<br />
					ea<br />
					ra<br />
					ce<br />
					li<br />
					ch<br />
					ll<br />
					be<br />
					ma<br />
					si<br />
					om<br />
					ur</p>
				</td>
				<td valign="top">
					<p>the<br />
					and<br />
					ing<br />
					ion<br />
					tio<br />
					ent<br />
					ati<br />
					for<br />
					her<br />
					ter<br />
					hat<br />
					tha<br />
					ere<br />
					ate<br />
					his<br />
					con<br />
					res<br />
					ver<br />
					all<br />
					ons<br />
					nce<br />
					men<br />
					ith<br />
					ted<br />
					ers<br />
					pro<br />
					thi<br />
					wit<br />
					are<br />
					ess<br />
					not<br />
					ive<br />
					was<br />
					ect<br />
					rea<br />
					com<br />
					eve<br />
					per<br />
					int<br />
					est<br />
					sta<br />
					cti<br />
					ica<br />
					ist<br />
					ear<br />
					ain<br />
					one<br />
					our<br />
					iti<br />
					rat</p>
				</td>
				<td valign="top">
					<p>tion<br />
					atio<br />
					that<br />
					ther<br />
					with<br />
					ment<br />
					ions<br />
					this<br />
					here<br />
					from<br />
					ould<br />
					ting<br />
					hich<br />
					whic<br />
					ctio<br />
					ence<br />
					have<br />
					othe<br />
					ight<br />
					sion<br />
					ever<br />
					ical<br />
					they<br />
					inte<br />
					ough<br />
					ance<br />
					were<br />
					tive<br />
					over<br />
					ding<br />
					pres<br />
					nter<br />
					comp<br />
					able<br />
					heir<br />
					thei<br />
					ally<br />
					ated<br />
					ring<br />
					ture<br />
					cont<br />
					ents<br />
					cons<br />
					rati<br />
					thin<br />
					part<br />
					form<br />
					ning<br />
					ecti<br />
					some</p>
				</td>				
				<td valign="top">
					<p>ation<br />
					tions<br />
					which<br />
					ction<br />
					other<br />
					their<br />
					there<br />
					ition<br />
					ement<br />
					inter<br />
					ional<br />
					ratio<br />
					would<br />
					tiona<br />
					these<br />
					state<br />
					natio<br />
					thing<br />
					under<br />
					ssion<br />
					ectio<br />
					catio<br />
					latio<br />
					about<br />
					count<br />
					ments<br />
					rougt<br />
					ative<br />
					prese<br />
					feren<br />
					hough<br />
					ution<br />
					roduc<br />
					resen<br />
					thoug<br />
					press<br />
					first<br />
					after<br />
					cause<br />
					where<br />
					tatio<br />
					could<br />
					efore<br />
					contr<br />
					hould<br />
					shoul<br />
					tical<br />
					gener<br />
					esent<br />
					great</p>
				</td>
				<td valign="top">
					<p>ations<br />
					ration<br />
					tional<br />
					nation<br />
					ection<br />
					cation<br />
					lation<br />
					though<br />
					presen<br />
					tation<br />
					should<br />
					resent<br />
					genera<br />
					dition<br />
					ationa<br />
					produc<br />
					throug<br />
					hrough<br />
					etween<br />
					betwee<br />
					differ<br />
					icatio<br />
					people<br />
					iffere<br />
					fferen<br />
					struct<br />
					action<br />
					person<br />
					eneral<br />
					system<br />
					relati<br />
					ctions<br />
					ecause<br />
					becaus<br />
					before<br />
					ession<br />
					develo<br />
					evelop<br />
					uction<br />
					change<br />
					follow<br />
					positi<br />
					govern<br />
					sition<br />
					merica<br />
					direct<br />
					bility<br />
					effect<br />
					americ<br />
					public</p>														
			</tr>
		</tbody>
	</table>
	
	<p class="sizelabel" style="margin-bottom: 10px;">32px Most common 20 letter words</p>
	<table width="900px">
		<tbody>
			<tr>
				<td valign="top">
					<p>electroencephalographic<br />
					polytetrafluoroethylene<br />
					forschungsgemeinschaft<br />
					deinstitutionalization<br />
					counterrevolutionaries<br />
					dehydroepiandrosterone<br />
					electroencephalography<br />
					immunoelectrophoresis<br />
					institutionalisation<br />
					acetylcholinesterase<br />
					internationalization<br />
					institutionalization</p>
				</td>
				<td valign="top">
					<p>radiopharmaceuticals<br />
					electroencephalogram<br />
					keratoconjunctivitis<br />
					counterrevolutionary<br />
					immunohistochemistry<br />
					internationalisation<br />
					hypercholesterolemia<br />
					phosphatidylinositol<br />
					compartmentalization<br />
					electrophysiological<br />
					electrocardiographic<br />
					uncharacteristically</p>
				</td>
			</tr>
		</tbody>
	</table>
	
</div>	