<div contenteditable="true">

	<div class="dontprint">
		<input type="range" min="12" max="200" value="16" step="1" oninput="changeFontSizeOldNick(this.value)" onchange="changeFontSizeOldNick(this.value)" style="width: 400px;" />
		<input type="range" min="0.6" max="2" value="1.5" step="0.01" oninput="changeLineHeigthOldNick(this.value)" onchange="changeLineHeigthOldNick(this.value)" style="width: 200px;" />
		<script type="text/javascript">
			function changeFontSizeOldNick(newValue) {
				document.getElementById("changedfontsizeOldNick").innerHTML=newValue;
				$('.changesizeOldNick').css('font-size',newValue + 'px');
			};
			function changeLineHeigthOldNick(newValue) {
				document.getElementById("changedlineheigthOldNick").innerHTML=newValue;
				$('.changesizeOldNick').css('line-height',newValue);
			};
		</script>
	</div>

	<p class="sizelabel"><span id="changedfontsizeOldNick">16</span>px / <span id="changedlineheigthOldNick">1.5</span>em</p>
	<p class="sizelabel">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">If ANYONE wishes to believe me a little loony—which, might be possible, considering that I have quite intentionally made a considerable effort to insinuate that possibility indubitably—may now consider the preceding—as well as the following—proof more or less conclusive. Trust me on this.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">The glyph most representative of what 666 is alleged to represent is…$</p>
	<p class="changesizOldNicke" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Why? Because a money-changer (who changes money in the opposite direction from which Jesus would, I figure, do) walked into a temple (in name only; details to follow) which, I suspect, is Christian in name only (doh!), declared that all the money in the temple was Caesar's (if he gets the job and, brother, is Mitt THE right tool for the right job; details to follow), all of which should—again, predicated on the ridiculous notion that I have a clue what Jesus would actually do in any given situation, much less this: if what I can only assume to be true from the so-called reality which ALMOST everyone else on the planet is true, then Jesus has every right to be pissed—as he is alleged to have done in the only “credible” source on the subject, written by profits (this is NOT a typo) who profited ($ or functional equivalent) by peddling every word that they put into the mouth of God is the Absolute Gospel Truth (math majors: prove the inevitability of the conclusions, based on the premises).</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">And who profits from the word of the prophets who peddle the profits based on the most advantageous “Word of God”?</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Who allegedly knew that money only had as much power as you give it (which, according to the Supreme Court—who look nothing like the Supremes, nor as they nearly as smart in ANY sense of the word) is UNLIMITED—simply if you believe it? Who buys every word of it here—every time they get an inkling that the “big money guys” will screw with them…personally, by helping…me?…in ANY way…even to the point of denying me a free beer? Doh! Duh! I still find it amusing.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">So, I figure: believe in God (who is Love) or believe in 666, which is $. Each is as real as you believe it to be (welcome to the internet: Marshall MacLuhan WARNED it would be spell-binding). Believe in Heaven on Earth (could it REALLY be ANYWHERE else?); or believe in Hell: right here, right now, QED. Tragedy? Comedy? Happy ending? Or the end of the world? Or believe that loon Ron Paul? John Lennon was pretty much right, every time he opened his mouth—and he wound up dead. So did Jesus—but he had a hell of an out, which I no longer have any credible reason is true, since it’s based on making a profit from people killing themselves as quickly as possible. Devout Muslims score big-time on this one; however, a true believer is a true believer, no matter which words you use—which a true Muslin was so openly joyous when he missed the first chance to share the truths of his heart with someone as nutty as to walk into an Indian restaurant, run by Pakistani Muslims who were fasting for Ramadan but could NOT, UNDER ANY CIRCUMSTANCES accept a NON-ALCOHOLIC—0.0% (Halal++), bought from the corner grocery the owner’s Muslim brother ran and have the temerity to ask anyone to not share a beer in exchanging for confessing the things his heart which he believes to be ABSOLUTELY TRUE…</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Well, imagine my joy on such a chance (not a chance) meeting in which we placed our hands on each other’s hearts and testified…</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Precisely the same words, except…I did so in English, and he did so in Urdu (lucky for me, you and the whole world, potentially), only in different words. Duh. Doh. Uh-oh.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">God gave you free will: exercise and create the future, or relive the past (Go, George Santayana!). If you have been paying attention, I have given you no choice: toast my old man in Wilwaukee and take the pledge (available online—if you can find it), or the world ends…your $666$ way. Who are you going to believe? Well, if Lozos will deliver the rimshot: me. If you can’t take a joke, I am dying anyway. Which is inevitable and hopeless—unless it isn’t and Alan Watts is right. And if NOBODY can take this joke…the punchline is inevitable eight ways to Sunday: cash, credit, as unreal as possible (preferably ACH!!!), but only Amex under very special circumstances…like, when Hell freezes over.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">P.S. As soon as lightning strikes twice in the same place (God only know that) at some time (ditto), either Cassandra (probably) or Tinkerbelle (I hope) will get the predicted ending. Scholarly folk: clue them in and, in this context, the context of the former is important, because the context is actually where reality started getting taken out of context, which is reality—precisely as nature intended it.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Make a copy quick: Western Civilization is going down if I, personally, as God has made abundantly clear through his one and only non-profit prophet (I did not ask for this job) if one sober person in this joint will not at least OFFER to buy me a beer, for fear of pissing off the big money which exists only because you believe in money, but you do not believe in Love. Or free beer. No joke. Seriously.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">&nbsp;</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">P.S. In case anyone doubts that I might have reason to be paranoid.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">On paper is still real; going viral is not confined to the internet. I got back-up: Army, Navy, former Maximum Security Prison guard, regular folks, large muscular black men, dogs, regular folk—peppered all over. Take us all on (you MAY already know who they are) if you can find them (disregard previous message), or wipe us all out.</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Caution: Mormon virgins nearby. Sacrifice them and PROVE just how barbaric you aren't. Even if this message never actually reaches the internet (I firmly believe that almost anything is possible, but prefer to assign as little credibility to the uncomfortable stuff, unless given credible reason to believe so), it got through to the right folks. If so, wipe us out—I have made a pretty good case where the impossible might inevitably happen, only now the time is the only issue. Proofs of this promise supposedly existed in the White House when I tossed it out. If it turns up not to be there, tell me something I might not have anticipated. Because what I don't know will, in fact kill me—but (yo, Fred) what does not kill me…</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Pray I am wrong and I am dead. Pray I am right, and do it the right way—to God, who must necessarily exist in order to pray. Doh!</p>
	<p class="changesizeOldNick" style="font-size: 16px; line-height: 1.5em;">Rimshot, dammit! Or gunshot. Or freak lightning from nowhere, or plausible probability of something kinda like it. I did ask for it, didn't I? Language people: decipher this before 666 does...</p>

</div>	